### ISSUE TITLE
Document standards implementation status

### ISSUE THREAD

**Issue by da2x** [inferiorhumanorgans/meishi#1]
Please provide documentation about standards implementation in the project. For use in the Wikipedia [server implementation comparison article.](http://en.wikipedia.org/wiki/Comparison_of_CalDAV_and_CardDAV_implementations#Server_implementations)

**Comment by inferiorhumanorgans** [comment]
I've edited the Wiki page to reflect the current status.  For right now I'm working on a test suite to determine compliance, but I'm unsure how far into the depths of standards compliance I want to go so there's no formal documentation (yet).

**Comment by inferiorhumanorgans** [comment]
Also, README.md has been updated to indicate my current intent.
