### ISSUE TITLE
iPhone contact integration

### ISSUE THREAD

**Issue by pavoni** [inferiorhumanorgans/meishi#10]
This could be really useful for something I'd link to do, providing an address book from our Rails app.

I have it working with OSX iCal - and linked to my iPhone.

I can add contacts fine on the iPhone - and see them in the Rails app, but not back on the iPhone.

Also contacts added in the phone don't show up on the OSX app.

Just checking what should work / what not.

**Comment by inferiorhumanorgans** [comment]
What versions of OSX and iOS?

**Comment by pavoni** [comment]
IOS 7.0.5
OSX 10.9.1

If I compare the database with changes I make in Contacts - everything on OSX looks to work perfectly.

IOS is connecting - but not retrieving or adding contacts. Not 100% sure what is failing.

Don't know if this trace might help, looks to be an error log:-

```
Started PROPFIND "/book/1/" for 192.168.1.81 at 2014-02-18 18:01:09 +0000
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."username" = 'greg' LIMIT 1
   (0.1ms)  BEGIN
   (0.2ms)  UPDATE "users" SET "last_sign_in_at" = '2014-02-18 18:01:09.802652', "current_sign_in_at" = '2014-02-18 18:01:09.903386', "sign_in_count" = 411, "updated_at" = '2014-02-18 18:01:09.903865' WHERE "users"."id" = 1
   (0.8ms)  COMMIT
PUBLIC PATH '"/book/1"'
NEW PUBLIC PATH '"/book/1"'
is_contact = false; is_book = true; is_root = false
  AddressBook Load (0.2ms)  SELECT "address_books".* FROM "address_books" WHERE "address_books"."id" = 1 AND "address_books"."user_id" = 1 LIMIT 1
ABR::exist?(/book/1)
ABR::children(/book/1)
  Contact Load (0.3ms)  SELECT "contacts".* FROM "contacts" WHERE "contacts"."address_book_id" = 1
Trying to create this child (contact): 8aefd2ad-1e09-408a-a0b0-11c72ce3cf2d
```

**Comment by pavoni** [comment]
Should perhaps add that @address_book.nil? returns false - and address_book has a valid value. Which all looks OK to me.

If I trace through in Ruby debug - I can see the contact being added on the phone - and then vanishing as it it syncs to the server.
