### ISSUE TITLE
synchronization with sogo is broken

### ISSUE THREAD

**Issue by hannesm** [inferiorhumanorgans/meishi#3]
I have sogo installed - http://www.sogo.nu/files/downloads/extensions/sogo-connector-10.0.2.xpi

When I do a synchronization, all I see on the meishi side is:

```
Started PROPFIND "/book/1/" for 213.73.89.219 at 2012-07-05 15:59:26 +0200
/usr/local/lib/ruby/gems/1.9/bundler/gems/dav4rack-ab3404cd5b43/lib/dav4rack/controller.rb:37:in `url_unescape': warning: URI.unescape is obsolete
/usr/local/lib/ruby/gems/1.9/bundler/gems/dav4rack-ab3404cd5b43/lib/dav4rack/controller.rb:37:in `url_unescape': warning: URI.unescape is obsolete
PUBLIC PATH '"/book/1"'
NEW PUBLIC PATH '"/book/1"'
is_contact = false; is_book = true; is_root = false
ABR::exist?(/book/1)
/usr/local/lib/ruby/gems/1.9/bundler/gems/dav4rack-ab3404cd5b43/lib/dav4rack/controller.rb:27:in `url_format': warning: URI.escape is obsolete
Base::get_book_property({:name=>"resourcetype", :ns_href=>"DAV:", :children=>[], :attributes=>{}})
Base::get_book_property({:name=>"supported-report-set", :ns_href=>"DAV:", :children=>[], :attributes=>{}})
Base::get_book_property({:name=>"getctag", :ns_href=>"http://calendarserver.org/ns/", :children=>[], :attributes=>{}})

```

And no contact is synced

**Comment by inferiorhumanorgans** [comment]
I can confirm that SoGo sees contacts with the latest commit.

**Comment by hannesm** [comment]
thanks for your patches

but I still can't see any contacts in Sogo -- and yes, I use /book/1/ in sogo (your question from #2). Works fine with android carddav and macosx address book, though.

**Comment by hannesm** [comment]
the log output of address book syncing is:

```
Started PROPFIND "/book/1/" for 213.73.89.219 at 2012-07-06 14:14:21 +0200
/usr/local/lib/ruby/gems/1.9/bundler/gems/dav4rack-ab3404cd5b43/lib/dav4rack/controller.rb:37:in `url_unescape': warning: URI.unescape is obsolete
/usr/local/lib/ruby/gems/1.9/bundler/gems/dav4rack-ab3404cd5b43/lib/dav4rack/controller.rb:37:in `url_unescape': warning: URI.unescape is obsolete
PUBLIC PATH '"/book/1"'
NEW PUBLIC PATH '"/book/1"'
is_contact = false; is_book = true; is_root = false
ABR::exist?(/book/1)
ABR::children(/book/1)
Exception `NameError' at /usr/local/lib/ruby/gems/1.9/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:520 - uninitialized constant AddressBook::Contact
Exception `NameError' at /usr/local/lib/ruby/gems/1.9/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:202 - uninitialized constant AddressBook::Contact
Trying to create this child (contact): 4e5eaa3b-9512-4afa-8f84-ba475a8c87b4
PUBLIC PATH '"/book/1/4e5eaa3b-9512-4afa-8f84-ba475a8c87b4"'
NEW PUBLIC PATH '"/book/1/4e5eaa3b-9512-4afa-8f84-ba475a8c87b4"'
is_contact = true; is_book = false; is_root = false
Trying to create this child (contact): b775b128-8acd-4181-9472-39664adf3cad
PUBLIC PATH '"/book/1/b775b128-8acd-4181-9472-39664adf3cad"'
NEW PUBLIC PATH '"/book/1/b775b128-8acd-4181-9472-39664adf3cad"'
is_contact = true; is_book = false; is_root = false
Trying to create this child (contact): 88dbeb50-6b07-47c3-b90c-e6cc0f206b9c
PUBLIC PATH '"/book/1/88dbeb50-6b07-47c3-b90c-e6cc0f206b9c"'
```

followed by get requests for each contact
`Started GET "/book/1/eb9ab986-7a91-4739-ad64-bd8c480c70c3" for 213.73.89.219 at 2012-07-06 14:14:23 +0200`

**Comment by hannesm** [comment]
still not clear to me whether this is on the sogo side or the meishi side -- I'm running meishi from master, and latest sogo connector release (10.0.2) on thunderbird 13.0.1 on macosx 10.7.4... any help is appreciated!

**Comment by inferiorhumanorgans** [comment]
Currently I'm using Thunderbird 14.0 with Sogo 10.0.1 and Sogo 10.0.3, so far so good.  From the log output you've posted, something looks amiss (you shouldn't be seeing any exceptions).

Can you confirm which version of meishi you're running?  I'm using a clean install of 6fc6f21394 with no problems so far.

**Comment by hannesm** [comment]
I'm running 6fc6f21394a6cc9a1d17290946ef957b566dc4b9 with some debug output:

```
--- a/app/models/carddav/base_resource.rb
+++ b/app/models/carddav/base_resource.rb
@@ -79,8 +79,10 @@ module Carddav
         # Let's just humor it.
         if self.respond_to?(fn)
           if element[:children].empty? and element[:attributes].empty?
+            Rails.logger.error "Base::get_book_property with empty stuff #{fn.to_sym}"
             return self.send(fn.to_sym)
           else
+            Rails.logger.error "Base::get_book_property with non-empty stuff #{fn.to_sym} child: #{element[:children]} attr #{element[:attributes]}"
             return self.send(fn.to_sym, element[:attributes], element[:children])
           end
         end
@@ -173,4 +175,4 @@ module Carddav
     end

   end
-end
\ No newline at end of file
+end
```

and Sogo connector 10.0.2, thunderbird 14 on MacOSX (doesn't work on FreeBSD either)

**Comment by hannesm** [comment]
(same with 10.0.3)

**Comment by inferiorhumanorgans** [comment]
Can you see the contacts in the web interface?  If so, what do the vCards (append .vcf to download the raw vCard) look like?

**Comment by hannesm** [comment]
http://opendylan.org/~hannes/XXX/1.png and http://opendylan.org/~hannes/XXX/2.png

**Comment by hannesm** [comment]
and http://opendylan.org/~hannes/XXX/ebe4691c-1dc4-46d9-afa1-f539d74f5a50.vcf

**Comment by inferiorhumanorgans** [comment]
Is SoGo downloading the vCard?  Can you try this with a contact created as a person and not a company?

**Comment by hannesm** [comment]
sogo does not download anything as far as I can tell from the log. it is also not syncing a contact created in thunderbird.

[login credentials redacted]

**Comment by inferiorhumanorgans** [comment]
As of e645051252, you can enable logging of the XML requests and responses.  Can you set MEISHI_DEBUG_XML_REQUEST and MEISHI_DEBUG_XML_RESPONSE to 2, go through the motions, and email me the resulting development.log file?

**Comment by hannesm** [comment]
no, sorry - I switched to a different carddav server in order to have something usable
