### ISSUE TITLE
Blackberry 10 Support

### ISSUE THREAD

**Issue by singpolyma** [inferiorhumanorgans/meishi#9]
I'm working on getting this sync'ing with my BB10 device.

One note, nothing to do with you, but in case others come looking: no matter what you say BB10 always only tries over HTTPS.

I'm getting a lot of things like:

```
ArgumentError (wrong number of arguments (2 for 0)):
  app/models/carddav/base_resource.rb:131:in `current_user_principal'
  app/models/carddav/base_resource.rb:84:in `get_property'
```

My current hack is just to mod these methods to take any number of arguments, but it seems like there's something going wrong here?

Also, BB10 seems to really want full URIs (as per spec) instead of paths (comments indicate this is a hack to appease OSX)

**Comment by singpolyma** [comment]
Hmm... it also seems to reject redirects.  I can give it the `/carddav/` path, but it forgets it after the first connection.

**Comment by singpolyma** [comment]
I got adding to work, but it doesn't seem to actually by syncing any content.  Hmm...

**Comment by inferiorhumanorgans** [comment]
Okay. I'm looking at setting up an instance of the BB10 emulator, but for the time being, any chance you can log the request being sent?

The exceptions you're getting are indeed errors.  The functions that return element info (ex: current_user_principal) take either zero arguments (no attributes specified in the request) or two arguments (if attributes are specified in the request).  The functions that are defined to take no arguments are ones that (in my testing) don't include any additional attributes.  The best practice here is to ensure that they all handle zero or two arguments.  As a first step, getting the XML that the BB client is sending would be great.  That may explain why syncing isn't working.

The full paths could/should be turned into a tuneable option (and may relate to why the BB client can't handle redirects).

The HTTPS issue is up to RIM to solve.

**Comment by inferiorhumanorgans** [comment]
Okay as of 7f290a0 Meishi should default to sending out proper URLs.  This may (or may not) fix the redirection issue (if the principal URL wasn't recognized by the BB client...).  If you can get me the XML requests and responses that'd be great (the BB10 simulator is a mess on OSX).  As of 57db00dce9, you can control XML logging with the MEISHI_DEBUG_XML_REQUEST and MEISHI_DEBUG_XML_RESPONSE environment variables.

**Comment by inferiorhumanorgans** [comment]
Okay here's how things look to me:

With BB10.1 the CardDAV client is completely broken.  It ignores the specification of a principal URL, ignores redirects from the root URL, and it doesn't attempt to use RFC 5785 based autodiscovery.

With BB10.2 these bugs are fixed and replaced by an improper addressbook-multiget REPORT request.  The depth is set to 1, where RFC 6352 is quite clear that this is improper.  I'll add a quirk, but the BB10 contacts library doesn't send a particularly useful user-agent.

**Comment by singpolyma** [comment]
Sorry for not getting back to this sooner.  Looks like you figured it out, though.  Awesome!  Thanks!  Yet another reason I have to await the 10.2 official release.

**Comment by inferiorhumanorgans** [comment]
No worries. If it breaks again in 10.2, please reopen this issue.
